Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: C:/Users/Aryan  gupta/Desktop/SEASOR CIPHER.PY ===========
Enter String: ARYANMOTILALGUPTA
Enter Shift Number: 1
1. For Encrypt
2. For Decrypt
Enter Your Option: 1
Original String: ARYANMOTILALGUPTA
After Encryption: BSZBONPUJMBMHVQUB
>>> 
============ RESTART: C:/Users/Aryan  gupta/Desktop/SEASOR CIPHER.PY ===========
Enter String: BSZBONPUJMBMHVQUB
Enter Shift Number: 1
1. For Encrypt
2. For Decrypt
Enter Your Option: 2
Original String: BSZBONPUJMBMHVQUB
After Decryption: ARYANMOTILALGUPTA
>>> 
>>> 
